/**
 * ExtensionInstallCenter — Dashboard component (v2.1)
 *
 * Changes from v2.0:
 *  - Download button links to the real /adaptive-shield-extension.zip
 *  - chrome://extensions link replaced with a copy-to-clipboard button
 *    (browsers block direct href="chrome://..." navigation)
 *  - 4-step install guide matches the exact requested workflow
 *  - Connected state shows detailed live stats + heuristic count
 */

import React, { useState } from 'react';
import {
  Download, Shield, CheckCircle, ChevronRight, Copy,
  Globe2, AlertTriangle, Zap, Eye, Bell, Radio, Check,
  FolderOpen, ToggleRight, MousePointer2
} from 'lucide-react';

// ── Install steps (4 explicit steps as requested) ──────────────────────────
const STEPS = [
  {
    n:     '01',
    title: 'Download & Extract the ZIP',
    desc:  'Click "Download Extension (.zip)" below. Once downloaded, extract the ZIP file — you\'ll get a folder named "adaptive-shield-extension". Keep this folder in a permanent location (e.g. your Documents folder).',
    icon:  Download,
    color: 'blue',
    code:  null,
  },
  {
    n:     '02',
    title: 'Open Chrome Extensions Page',
    desc:  'Open a new Chrome tab and type the following URL in the address bar, then press Enter. Browsers block direct links to chrome:// pages for security — you must copy and paste it yourself.',
    icon:  Globe2,
    color: 'sky',
    code:  'chrome://extensions',
  },
  {
    n:     '03',
    title: 'Enable Developer Mode',
    desc:  'On the Extensions page, find the "Developer mode" toggle in the top-right corner. Click it to turn it ON. You\'ll see new buttons appear: "Load unpacked", "Pack extension", and "Update".',
    icon:  ToggleRight,
    color: 'purple',
    code:  null,
  },
  {
    n:     '04',
    title: 'Load the Unpacked Extension',
    desc:  'Click "Load unpacked". A file-picker dialog opens. Navigate to and select the "adaptive-shield-extension" folder you extracted in Step 1. The extension will appear in your list immediately — pin it to your toolbar by clicking the puzzle-piece icon.',
    icon:  FolderOpen,
    color: 'emerald',
    code:  null,
  },
];

const colorMap = {
  blue:    { bg: 'bg-blue-600/10',    border: 'border-blue-500/30',    text: 'text-blue-400',    icon: 'bg-blue-600/20 text-blue-400'    },
  sky:     { bg: 'bg-sky-600/10',     border: 'border-sky-500/30',     text: 'text-sky-400',     icon: 'bg-sky-600/20 text-sky-400'      },
  purple:  { bg: 'bg-purple-600/10',  border: 'border-purple-500/30',  text: 'text-purple-400',  icon: 'bg-purple-600/20 text-purple-400' },
  emerald: { bg: 'bg-emerald-600/10', border: 'border-emerald-500/30', text: 'text-emerald-400', icon: 'bg-emerald-600/20 text-emerald-400' },
};

const FEATURES = [
  { icon: Eye,           label: 'Real-time URL scanning on every navigation' },
  { icon: Bell,          label: 'Native Chrome desktop notifications'        },
  { icon: AlertTriangle, label: 'On-screen red banner for HIGH/CRITICAL sites' },
  { icon: Shield,        label: 'Plain-English "Why flagged" explanations'   },
  { icon: Radio,         label: 'Live sync with this dashboard'              },
  { icon: Zap,           label: 'Zero external servers — 100% local'         },
];

// ── CopyButton component ─────────────────────────────────────────────────────
function CopyButton({ text, label = 'Copy' }) {
  const [copied, setCopied] = useState(false);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      // Fallback for browsers without clipboard API
      const ta = document.createElement('textarea');
      ta.value = text;
      ta.style.position = 'fixed';
      ta.style.opacity  = '0';
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <button
      onClick={handleCopy}
      className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
        copied
          ? 'bg-emerald-600/20 border border-emerald-500/40 text-emerald-400'
          : 'bg-sky-600/15 border border-sky-500/30 text-sky-300 hover:bg-sky-600/25'
      }`}
      title={`Copy "${text}" to clipboard`}
    >
      {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
      {copied ? 'Copied!' : label}
    </button>
  );
}

// ── Main component ──────────────────────────────────────────────────────────
export default function ExtensionInstallCenter({ isConnected = false, scannedCount = 0, flaggedCount = 0 }) {
  const [downloading, setDownloading] = useState(false);

  function handleDownload() {
    setDownloading(true);
    // The zip is generated by `npm run build` (scripts/build-extension-zip.mjs)
    // and placed at public/adaptive-shield-extension.zip → served at /adaptive-shield-extension.zip
    const a = document.createElement('a');
    a.href     = '/adaptive-shield-extension.zip';
    a.download = 'adaptive-shield-extension.zip';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => setDownloading(false), 2000);
  }

  // ── Connected state ───────────────────────────────────────────────────────
  if (isConnected) {
    return (
      <section className="px-4 sm:px-6 lg:px-12 py-10">
        <div className="max-w-4xl mx-auto rounded-3xl bg-emerald-950/30 border border-emerald-700/40 p-6 sm:p-8">
          <div className="flex flex-col sm:flex-row sm:items-center gap-6">
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 rounded-2xl bg-emerald-600/20 border border-emerald-500/30 flex items-center justify-center text-2xl shrink-0">
                🛡️
              </div>
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <h2 className="text-lg font-bold text-white">AdaptiveShield Extension Active</h2>
                  <span className="flex items-center gap-1 text-[10px] font-mono font-bold px-2 py-0.5 rounded-full bg-emerald-950 border border-emerald-700 text-emerald-400">
                    <Radio className="w-2.5 h-2.5 animate-pulse" /> MONITORING
                  </span>
                </div>
                <p className="text-sm text-emerald-300/70">Your browser is protected in real time.</p>
                <div className="flex flex-wrap gap-3 mt-2">
                  {FEATURES.slice(0, 3).map(({ icon: Icon, label }) => (
                    <div key={label} className="flex items-center gap-1.5 text-[10px] text-emerald-400/70">
                      <Icon className="w-3 h-3 shrink-0" />{label}
                    </div>
                  ))}
                </div>
              </div>
            </div>
            <div className="sm:ml-auto flex gap-6">
              {[
                { val: scannedCount, lbl: 'URLs Scanned',  color: 'text-blue-400'   },
                { val: flaggedCount, lbl: 'Threats Found', color: 'text-rose-400'   },
              ].map(({ val, lbl, color }) => (
                <div key={lbl} className="text-center">
                  <div className={`text-3xl font-extrabold font-mono ${color}`}>{val}</div>
                  <div className="text-[10px] text-slate-500 font-mono uppercase tracking-wide mt-0.5">{lbl}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
    );
  }

  // ── Install guide ─────────────────────────────────────────────────────────
  return (
    <section className="px-4 sm:px-6 lg:px-12 py-14" id="install-extension">
      <div className="max-w-5xl mx-auto space-y-10">

        {/* Hero card */}
        <div className="rounded-3xl bg-gradient-to-br from-blue-950/60 via-slate-900/80 to-indigo-950/60 border border-blue-500/25 p-6 sm:p-10 relative overflow-hidden">
          <div className="pointer-events-none absolute -top-20 -right-20 w-64 h-64 rounded-full bg-blue-600/10 blur-3xl" />
          <div className="relative z-10 flex flex-col lg:flex-row lg:items-start gap-8">
            <div className="flex-1 space-y-4">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-600/15 border border-blue-500/30 text-blue-300 text-xs font-mono font-semibold">
                <Shield className="w-3.5 h-3.5" />
                FREE CHROME EXTENSION — MANIFEST V3
              </div>

              <h2 className="text-2xl sm:text-3xl font-extrabold text-white leading-tight">
                Protect Your Browser with{' '}
                <span className="bg-gradient-to-r from-blue-400 to-sky-300 bg-clip-text text-transparent">
                  AdaptiveShield
                </span>
              </h2>

              <p className="text-slate-400 text-sm sm:text-base leading-relaxed max-w-xl">
                Real-time phishing detection, on-screen security alerts, and plain-English
                threat explanations — running entirely inside your browser with zero data
                sent to any external server.
              </p>

              <div className="flex flex-wrap gap-3">
                {[
                  'No account required',
                  '100% local processing',
                  'Open source & auditable',
                ].map(f => (
                  <div key={f} className="flex items-center gap-1.5 text-xs font-semibold text-emerald-400">
                    <CheckCircle className="w-3.5 h-3.5" /> {f}
                  </div>
                ))}
              </div>

              <div className="flex flex-wrap gap-3 pt-1">
                <button
                  onClick={handleDownload}
                  disabled={downloading}
                  className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-500 active:bg-blue-700 text-white font-bold text-sm shadow-lg shadow-blue-600/25 transition-all cursor-pointer disabled:opacity-60"
                >
                  <Download className="w-4 h-4" />
                  {downloading ? 'Downloading…' : 'Download Extension (.zip)'}
                </button>
              </div>

              {/* chrome:// copy block */}
              <div className="rounded-xl bg-slate-900/80 border border-slate-700/60 p-3 flex flex-col sm:flex-row sm:items-center gap-3 mt-2">
                <div className="flex-1">
                  <p className="text-[11px] font-semibold text-slate-300 mb-0.5">
                    After downloading, open Chrome's Extensions page:
                  </p>
                  <code className="text-xs text-sky-400 font-mono">chrome://extensions</code>
                  <p className="text-[10px] text-slate-500 mt-0.5">
                    Browsers block direct links to chrome:// for security. Copy the URL and paste it in a new tab.
                  </p>
                </div>
                <CopyButton text="chrome://extensions" label="Copy URL" />
              </div>
            </div>

            {/* Feature list */}
            <div className="lg:w-60 space-y-2.5">
              <p className="text-[10px] font-mono font-bold text-slate-500 uppercase tracking-widest mb-3">What You Get</p>
              {FEATURES.map(({ icon: Icon, label }) => (
                <div key={label} className="flex items-start gap-2 text-xs text-slate-400">
                  <Icon className="w-3.5 h-3.5 text-blue-400 shrink-0 mt-0.5" />
                  {label}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* 4-step install guide */}
        <div>
          <div className="text-center mb-8 space-y-1">
            <h3 className="text-xl sm:text-2xl font-extrabold text-white">Install in 4 Steps</h3>
            <p className="text-slate-400 text-sm">No Chrome Web Store required — load it directly as an unpacked extension.</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {STEPS.map(({ n, title, desc, icon: Icon, color, code }, i) => {
              const c = colorMap[color];
              return (
                <div
                  key={n}
                  className={`p-5 rounded-2xl bg-slate-900/80 border ${c.border} hover:scale-[1.01] transition-all duration-200`}
                >
                  <div className="flex items-center gap-3 mb-3">
                    <div className={`w-10 h-10 rounded-xl ${c.icon} flex items-center justify-center shrink-0`}>
                      <Icon className="w-5 h-5" />
                    </div>
                    <span className={`text-xs font-mono font-bold ${c.text}`}>STEP {n}</span>
                  </div>
                  <h4 className="text-sm font-bold text-white mb-2">{title}</h4>
                  <p className="text-xs text-slate-400 leading-relaxed">{desc}</p>

                  {/* Inline copy block for the chrome:// step */}
                  {code && (
                    <div className="mt-3 flex items-center gap-2 p-2 rounded-lg bg-slate-800/80 border border-slate-700/50">
                      <code className="flex-1 text-xs text-sky-400 font-mono">{code}</code>
                      <CopyButton text={code} label="Copy" />
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>

        {/* Developer Mode warning */}
        <div className="rounded-2xl bg-amber-950/20 border border-amber-700/30 p-4 flex gap-3">
          <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
          <div className="text-xs text-amber-200/80 leading-relaxed space-y-1">
            <p>
              <strong className="text-amber-300">Developer Mode note:</strong>{' '}
              Chrome displays an "Extensions running in developer mode" banner when developer mode is enabled.
              This is expected for unpacked extensions and does not indicate anything unsafe.
              The AdaptiveShield source code is fully open and auditable in the{' '}
              <code className="text-amber-400">dist/</code> folder you downloaded.
            </p>
            <p>
              If you see a "Disable developer mode extensions" prompt after restarting Chrome, click
              "Keep" to keep AdaptiveShield running.
            </p>
          </div>
        </div>

      </div>
    </section>
  );
}
